// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

// blackhole-py runs CQ in a single fixed topology:
// - prefetch BRISC on (PREFETCH_NOC_X,PREFETCH_NOC_Y) with NOC_INDEX=0
// - dispatch BRISC on (DISPATCH_NOC_X,DISPATCH_NOC_Y) with NOC_INDEX=1
// - dispatch subordinate NCRISC on (DISPATCH_NOC_X,DISPATCH_NOC_Y) with NOC_INDEX=1
// Keep this file explicit and static so CQ behavior is easy to reason about.

#define DISPATCH_KERNEL 1
#define FD_CORE_TYPE 0
#define IS_H_VARIANT 1
#define IS_D_VARIANT 1

// PREFETCH_NOC_X/Y and DISPATCH_NOC_X/Y come from -D flags (board-specific)

#if defined(COMPILE_FOR_BRISC) && (NOC_INDEX == 0)
// cq_prefetch.cpp
#define MY_NOC_X PREFETCH_NOC_X
#define MY_NOC_Y PREFETCH_NOC_Y
#define UPSTREAM_NOC_X PREFETCH_NOC_X
#define UPSTREAM_NOC_Y PREFETCH_NOC_Y
#define DOWNSTREAM_NOC_X DISPATCH_NOC_X
#define DOWNSTREAM_NOC_Y DISPATCH_NOC_Y
#define DOWNSTREAM_SUBORDINATE_NOC_X DISPATCH_NOC_X
#define DOWNSTREAM_SUBORDINATE_NOC_Y DISPATCH_NOC_Y
#define UPSTREAM_NOC_INDEX 0

#define DOWNSTREAM_CB_BASE 0x1A000
#define DOWNSTREAM_CB_LOG_PAGE_SIZE 12
#define DOWNSTREAM_CB_PAGES 128
#define MY_DOWNSTREAM_CB_SEM_ID 0
#define DOWNSTREAM_CB_SEM_ID 0

#define PCIE_BASE 0x40000100
#define PCIE_SIZE (64 * 1024 * 1024)
#define PREFETCH_Q_BASE 0x19840
#define PREFETCH_Q_SIZE 0xBFC
#define PREFETCH_Q_RD_PTR_ADDR 0x196C0
#define PREFETCH_Q_PCIE_RD_PTR_ADDR 0x196C4

#define CMDDAT_Q_BASE 0x1A440
#define CMDDAT_Q_SIZE (256 * 1024)
#define SCRATCH_DB_BASE 0x5A440
#define SCRATCH_DB_SIZE (128 * 1024)
#define DOWNSTREAM_SYNC_SEM_ID 2
#define CMDDAT_Q_PAGES 64
#define MY_UPSTREAM_CB_SEM_ID 3
#define UPSTREAM_CB_SEM_ID 3
#define CMDDAT_Q_LOG_PAGE_SIZE 12
#define CMDDAT_Q_BLOCKS 4

#define DISPATCH_S_BUFFER_BASE 0x9A000
#define MY_DISPATCH_S_CB_SEM_ID 1
#define DOWNSTREAM_DISPATCH_S_CB_SEM_ID 0
#define DISPATCH_S_BUFFER_SIZE (32 * 1024)
#define DISPATCH_S_CB_LOG_PAGE_SIZE 8
#define RINGBUFFER_SIZE 0

#elif defined(COMPILE_FOR_BRISC) && (NOC_INDEX == 1)
// cq_dispatch.cpp
#define MY_NOC_X DISPATCH_NOC_X
#define MY_NOC_Y DISPATCH_NOC_Y
#define UPSTREAM_NOC_X PREFETCH_NOC_X
#define UPSTREAM_NOC_Y PREFETCH_NOC_Y
#define DOWNSTREAM_NOC_X DISPATCH_NOC_X
#define DOWNSTREAM_NOC_Y DISPATCH_NOC_Y
#define DOWNSTREAM_SUBORDINATE_NOC_X DISPATCH_NOC_X
#define DOWNSTREAM_SUBORDINATE_NOC_Y DISPATCH_NOC_Y
#define UPSTREAM_NOC_INDEX 0

#define DISPATCH_CB_BASE 0x1A000
#define DISPATCH_CB_LOG_PAGE_SIZE 12
#define DISPATCH_CB_PAGES 128
#define DISPATCH_CB_BLOCKS 4
#define MY_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_SYNC_SEM 2

#define COMMAND_QUEUE_BASE_ADDR 0x40000000
#define COMPLETION_QUEUE_BASE_ADDR 0x44000100
#define COMPLETION_QUEUE_SIZE (32 * 1024 * 1024)
#define HOST_COMPLETION_Q_WR_PTR 128
#define DEV_COMPLETION_Q_WR_PTR 0x196D0
#define DEV_COMPLETION_Q_RD_PTR 0x196E0

#define DOWNSTREAM_CB_BASE 0
#define DOWNSTREAM_CB_SIZE 0
#define MY_DOWNSTREAM_CB_SEM_ID 1
#define DOWNSTREAM_CB_SEM_ID 1

#define SPLIT_DISPATCH_PAGE_PREAMBLE_SIZE 0
#define SPLIT_PREFETCH 0
#define PREFETCH_H_NOC_XY 0
#define PREFETCH_H_LOCAL_DOWNSTREAM_SEM_ADDR 0
#define PREFETCH_H_MAX_CREDITS 0

#define PACKED_WRITE_MAX_UNICAST_SUB_CMDS 118
#define DISPATCH_S_SYNC_SEM_BASE_ADDR 0x19710
#define MAX_NUM_WORKER_SEMS 8
#define MAX_NUM_GO_SIGNAL_NOC_DATA_ENTRIES 256
#define MCAST_GO_SIGNAL_ADDR 0x370
#define UNICAST_GO_SIGNAL_ADDR 0x370
#define DISTRIBUTED_DISPATCHER 0
#define FIRST_STREAM_USED 48
#define VIRTUALIZE_UNICAST_CORES 0
#define NUM_VIRTUAL_UNICAST_CORES 0
#define NUM_PHYSICAL_UNICAST_CORES 0
#define WORKER_MCAST_GRID 0x8102CE
#define NUM_WORKER_CORES_TO_MCAST 118

#elif defined(COMPILE_FOR_NCRISC) && (NOC_INDEX == 1)
// cq_dispatch_subordinate.cpp
#define MY_NOC_X DISPATCH_NOC_X
#define MY_NOC_Y DISPATCH_NOC_Y
#define UPSTREAM_NOC_X PREFETCH_NOC_X
#define UPSTREAM_NOC_Y PREFETCH_NOC_Y
#define DOWNSTREAM_NOC_X DISPATCH_NOC_X
#define DOWNSTREAM_NOC_Y DISPATCH_NOC_Y

#define CB_BASE 0x9A000
#define CB_LOG_PAGE_SIZE 8
#define CB_SIZE (32 * 1024)
#define MY_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_DISPATCH_CB_SEM_ID 1

#define DISPATCH_S_SYNC_SEM_BASE_ADDR 0x19710
#define MCAST_GO_SIGNAL_ADDR 0x370
#define UNICAST_GO_SIGNAL_ADDR 0x370
#define DISTRIBUTED_DISPATCHER 0
#define FIRST_STREAM_USED 48
#define MAX_NUM_WORKER_SEMS 8
#define MAX_NUM_GO_SIGNAL_NOC_DATA_ENTRIES 256
#define VIRTUALIZE_UNICAST_CORES 0
#define NUM_VIRTUAL_UNICAST_CORES 0
#define NUM_PHYSICAL_UNICAST_CORES 0
#define WORKER_MCAST_GRID 0x8102CE
#define NUM_WORKER_CORES_TO_MCAST 118

#else
#error "Unsupported CQ kernel variant for blackhole-py fixed config"
#endif
