// Generated from firmware/cq/cq_commands.hpp and firmware/cq/cq_fixed_config.hpp.
// Regenerate with `cargo run --manifest-path xtask/Cargo.toml -- update-cq-bindings`.

/* automatically generated by rust-bindgen 0.72.1 */

pub const DISPATCH_CB_PAGES: u32 = 128;
pub const COMPLETION_QUEUE_SIZE: u32 = 33554432;
pub const HOST_COMPLETION_Q_WR_PTR: u32 = 128;
pub const DEV_COMPLETION_Q_WR_PTR: u32 = 104144;
pub const DEV_COMPLETION_Q_RD_PTR: u32 = 104160;
pub const DISPATCH_S_SYNC_SEM_BASE_ADDR: u32 = 104208;
pub const FIRST_STREAM_USED: u32 = 48;
pub const CQ_DISPATCH_CMD_SIZE: u32 = 16;
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CQPrefetchCmdId {
    CQ_PREFETCH_CMD_ILLEGAL = 0,
    CQ_PREFETCH_CMD_RELAY_LINEAR = 1,
    CQ_PREFETCH_CMD_RELAY_LINEAR_H = 2,
    CQ_PREFETCH_CMD_RELAY_PAGED = 3,
    CQ_PREFETCH_CMD_RELAY_PAGED_PACKED = 4,
    CQ_PREFETCH_CMD_RELAY_INLINE = 5,
    CQ_PREFETCH_CMD_RELAY_INLINE_NOFLUSH = 6,
    CQ_PREFETCH_CMD_EXEC_BUF = 7,
    CQ_PREFETCH_CMD_EXEC_BUF_END = 8,
    CQ_PREFETCH_CMD_STALL = 9,
    CQ_PREFETCH_CMD_DEBUG = 10,
    CQ_PREFETCH_CMD_TERMINATE = 11,
    CQ_PREFETCH_CMD_PAGED_TO_RINGBUFFER = 12,
    CQ_PREFETCH_CMD_SET_RINGBUFFER_OFFSET = 13,
    CQ_PREFETCH_CMD_RELAY_RINGBUFFER = 14,
    CQ_PREFETCH_CMD_MAX_COUNT = 15,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CQDispatchCmdId {
    CQ_DISPATCH_CMD_ILLEGAL = 0,
    CQ_DISPATCH_CMD_WRITE_LINEAR = 1,
    CQ_DISPATCH_CMD_WRITE_LINEAR_H = 2,
    CQ_DISPATCH_CMD_WRITE_LINEAR_H_HOST = 3,
    CQ_DISPATCH_CMD_WRITE_PAGED = 4,
    CQ_DISPATCH_CMD_WRITE_PACKED = 5,
    CQ_DISPATCH_CMD_WRITE_PACKED_LARGE = 6,
    CQ_DISPATCH_CMD_WAIT = 7,
    CQ_DISPATCH_CMD_SINK = 8,
    CQ_DISPATCH_CMD_DEBUG = 9,
    CQ_DISPATCH_CMD_DELAY = 10,
    CQ_DISPATCH_CMD_EXEC_BUF_END = 11,
    CQ_DISPATCH_CMD_SET_WRITE_OFFSET = 12,
    CQ_DISPATCH_CMD_TERMINATE = 13,
    CQ_DISPATCH_CMD_SEND_GO_SIGNAL = 14,
    CQ_DISPATCH_NOTIFY_SUBORDINATE_GO_SIGNAL = 15,
    CQ_DISPATCH_SET_NUM_WORKER_SEMS = 16,
    CQ_DISPATCH_SET_GO_SIGNAL_NOC_DATA = 17,
    CQ_DISPATCH_CMD_TIMESTAMP = 18,
    CQ_DISPATCH_CMD_MAX_COUNT = 19,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQPrefetchRelayInlineCmd {
    pub dispatcher_type: u8,
    pub pad: u16,
    pub length: u32,
    pub stride: u32,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchWriteHostCmd {
    pub is_event: u8,
    pub pad1: u16,
    pub pad2: u32,
    pub length: u64,
}
pub const CQ_DISPATCH_CMD_PACKED_WRITE_LARGE_FLAG_UNLINK: u32 = 1;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchWritePackedLargeSubCmd {
    pub noc_xy_addr: u32,
    pub addr: u32,
    pub length_minus1: u16,
    pub num_mcast_dests: u8,
    pub flags: u8,
}
pub const CQ_DISPATCH_CMD_PACKED_WRITE_LARGE_MAX_SUB_CMDS: u32 = 35;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CQDispatchCmdPackedWriteLargeType {
    CQ_DISPATCH_CMD_PACKED_WRITE_LARGE_TYPE_UNKNOWN = 0,
    CQ_DISPATCH_CMD_PACKED_WRITE_LARGE_TYPE_CBS_SEMS_CRTAS = 1,
    CQ_DISPATCH_CMD_PACKED_WRITE_LARGE_TYPE_PROGRAM_BINARIES = 2,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchWritePackedLargeCmd {
    pub type_: u8,
    pub count: u16,
    pub alignment: u16,
    pub write_offset_index: u16,
}
pub const CQ_DISPATCH_CMD_WAIT_FLAG_WAIT_STREAM: u32 = 8;
pub const CQ_DISPATCH_CMD_WAIT_FLAG_CLEAR_STREAM: u32 = 16;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchWaitCmd {
    pub flags: u8,
    pub stream: u16,
    pub addr: u32,
    pub count: u32,
}
pub const CQ_DISPATCH_CMD_GO_NO_MULTICAST_OFFSET: u8 = 255;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchGoSignalMcastCmd {
    pub go_signal: u32,
    pub multicast_go_offset: u8,
    pub num_unicast_txns: u8,
    pub noc_data_start_index: u8,
    pub wait_count: u32,
    pub wait_stream: u32,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CQDispatchSetGoSignalNocDataCmd {
    pub pad1: u8,
    pub pad2: u16,
    pub num_words: u32,
}

// Constants generated from the prefetch BRISC fixed config.
/* automatically generated by rust-bindgen 0.72.1 */

pub const PREFETCH_Q_BASE: u32 = 104512;
pub const PREFETCH_Q_SIZE: u32 = 3068;
pub const PREFETCH_Q_RD_PTR_ADDR: u32 = 104128;
pub const PREFETCH_Q_PCIE_RD_PTR_ADDR: u32 = 104132;
